#
# Makefile
#
# Author: Shahu Ronghe (sronghe1@binghamton.edu)
# State University of New York at Binghamton
 
# Enables debug messages while compiling
baking: project01.c
	gcc -g project01.c -o baking_sim 

clean:
	rm baking_sim